In [1]:
import numpy as np
import random
np.version.version

'1.20.2'

In [2]:
rand = np.random.randint(0, 100, 16).reshape(4,4)
rand

array([[89, 91,  9, 94],
       [23, 49, 32, 71],
       [96, 40, 13, 70],
       [62, 15, 49,  6]])

In [3]:
type(rand)

numpy.ndarray

In [4]:
np.sum(rand)

809

In [5]:
np.max(rand, axis=1)

array([94, 71, 96, 62])

In [6]:
np.max(rand, axis=0)

array([96, 91, 49, 94])

In [9]:
man = [[random.randint(0,100) for x in range(5)] for y in range(5)]
man
np.max(man, axis=1)

array([78, 79, 89, 97, 99])

In [25]:
vec = np.random.randint(0, 1000, 100)
vec.shape

(100,)

In [26]:
np.argmax(vec)

43

In [27]:
np.max(vec)

995

In [30]:
nvec = vec.reshape(10,10)

In [31]:
np.average(nvec, axis=0)

array([566.4, 425.7, 581.5, 519.4, 412.4, 329. , 605.1, 386.7, 605.5,
       588.8])

In [32]:
np.average(nvec, axis=1)

array([661.4, 391.5, 488.1, 530.4, 397.5, 508.6, 593.8, 543.8, 528.1,
       377.3])

In [33]:
np.sum(nvec, axis=0)

array([5664, 4257, 5815, 5194, 4124, 3290, 6051, 3867, 6055, 5888])

In [34]:
np.sum(nvec, axis=1)

array([6614, 3915, 4881, 5304, 3975, 5086, 5938, 5438, 5281, 3773])